name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup UV
      uses: astral-sh/setup-uv@v3

    - name: Install dependencies
      run: bun install

    - name: Setup config
      run: |
        cp config.example.yaml config.yaml
        bun run build:config

    - name: Run builds
      run: bun run build

    # - name: Run tests
    #   run: bun run test