services:
  neo4j:
    image: neo4j:latest
    container_name: eda-neo4j
    ports:
      - "${NEO4J_HTTP_PORT}:7474"
      - "${NEO4J_BOLT_PORT}:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_PLUGINS=${NEO4J_PLUGINS}
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null -q http://localhost:7474 || exit 1"]
      interval: ${HEALTHCHECK_INTERVAL}s
      timeout: ${HEALTHCHECK_TIMEOUT}s
      retries: ${HEALTHCHECK_RETRIES}
    restart: always

volumes:
  neo4j_data: